version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2016-latest
    container_name: sqlserver_container
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123"
      MSSQL_DB: "sqlserver_db"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
