version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    container_name: oracle_container
    restart: always
    environment:
      ORACLE_PASSWORD: "Oracle123"
      ORACLE_SID: "ORCL"
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
